### PR TITLE
Issue-51: Update GUT Tests to assert if there are no orphans

### PR DESCRIPTION
**Pull request by Tysterman74**
# Description

Updating our test suite and action to be able to throw an error and fail the CI when there are orphans and if there is a compiler error.

## Related issue(s)

#51 

## List of changes

A more detailed list of the changes.
- Update CI.yml to use my forked action of the action workflow we're using
    - Added `-d` to my forked action to run the Godot command in debug, which throws an error if there are compiler errors 
- Updated all test suites that are instantiating objects to check for `assert_no_new_orphans("Orphans still exist, please free up test resources.")`

## Tests

Updated `test_cards.gd`, `test_health.gd`, and `test_pile_ui.gd` to check for no new orphans.

## Additional notes

Switched over to use my custom forked action: https://github.com/Tysterman74/godot-tester for running the unit tests. May need a sanity check for someone else to try running the CI with their PR to check it works for other users.

### CODE REVIEW

**Comment by Turtyo** [comment]
@Tysterman74 you forgot to actually write the context of the PR

**Comment by Tysterman74** [comment]
Ah yes I'll fill it in once I have the changes all good!

**Review by Turtyo — CHANGES_REQUESTED** [review]
I see you tested it indeed failed because of formatting errors. Could you also test that the "now new orphan" indeed fails ? Doing a push with a test that leaves orphans is probably the best way to do so.
If you could also update `test_event_base` with the same line as other tests file, it would be good

**Comment by Tysterman74** [comment]
> I see you tested it indeed failed because of formatting errors. Could you also test that the "now new orphan" indeed fails ? Doing a push with a test that leaves orphans is probably the best way to do so. If you could also update `test_event_base` with the same line as other tests file, it would be good

This commit here tested out the no new orphans assert! https://github.com/Saplings-Projects/1M_sub/actions/runs/7676114896/job/20923230430

I can work on updating the test_event_base.

**Comment by Turtyo** [comment]
Ah indeed I missed this commit!
Yes please, for `test_event_base`. Also since we merged #43 in `test_stats` also

**Comment by Turtyo** [comment]
If it's still passing even if you leave an orphan, there is something not working properly
just to be sure, which `queue_free` did you comment ? I know there are some redundant `queue_free` on enemies, because we do it on enemies and on battler, but the battler has a reference to the enemies so freeing the battler also frees the enemies

**Comment by Tysterman74** [comment]
Here's the commit that I tested the orphan assert: https://github.com/Saplings-Projects/1M_sub/pull/52/commits/fedc73f9348121555d658184083f7152501b331a CI marks it as a pass.

**Comment by Turtyo** [comment]
Indeed, quite strange
The idea behind detecting orphans was to see if there was an error in execution (since I noticed that every time it fails, there are orphans left). It was not to detect "actual" orphans left because forgotten in the `after_each`
Still strange this doesn't leave orphans, but that was not the idea anyway. I think it might be fine to merge as is, if we detect further problems (unless you have an idea to solve the problem now ?), and we monitor this to be sure for a bit

**Comment by Tysterman74** [comment]
I think it's fine to merge. Maybe when running the stats test it manages to clean up after itself before the after_each() is my theory.

**Review by Turtyo — APPROVED** [review]

**Review by cheesefrycook — APPROVED** [review]

**Pull request merged**
