### PR TITLE
Game menu

### PR DESCRIPTION
**Pull request by Paper-2**
# Description

Creates a more accessible menu for player to interact and look at.
## Related issue(s)

https://github.com/Saplings-Projects/1M_sub/issues/80

## List of changes

- Arrow keys can interact with the menu buttons.
- Added a version tag and title placeholder
- Added a prototype ish buttons for the menu UI

## Tests

No test are needed

### CODE REVIEW

**Review by Turtyo — CHANGES_REQUESTED** [review]
The new files in the `Art` directory do not follow the naming convention
Please rename them

The test for the naming convention might need some changes to work recursively, i'll think about it

**Comment by Turtyo** [comment]
I also notice the option button doesn't lead to the option menu anymore, apart from that it looks great !

**Review by Turtyo — COMMENTED** [review]
You forgot the lighted sub-directory I think

**Comment by Turtyo** [comment]
I notice that buttons can be activated by clicking on them, but they don't get lighted when they are just being hovered, do you know why maybe ?

**Review by Turtyo — APPROVED** [review]
Looking good :+1:

**Review by Lann-hyl — APPROVED** [review]

**Pull request merged**
